[DASH] Add support for ENI counters
vivekrnv/sonic-buildimage pull request #104
Opened 2024-07-12 22:07 UTC by vivekrnv

#### Why I did it

Add support for DASH ENI Counters

##### Work item tracking
- Microsoft ADO **(number only)**:

#### How I did it

Extend enable_counters.py script to enable the ENI counters only for DPU switch type

#### How to verify it

#### Which release branch to backport (provide reason below if selected)

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [ ] 202012
- [ ] 202106
- [ ] 202111
- [ ] 202205
- [ ] 202211
- [ ] 202305

#### Tested branch (Please provide the tested image version)

- [ ] 
- [ ] 

#### Description for the changelog

#### Link to config_db schema for YANG module changes

#### A picture of a cute animal (not mandatory but encouraged)

2024-08-02 17:19 UTC, oleksandrivantsiv commented on dockers/docker-orchagent/enable_counters.py
> +    if platform_info.get('switch_type', '') == 'dpu':
`''` is not needed. `None != 'dpu'`

2024-08-06 02:18 UTC, dgsudharsan requested changes
You need to extend sonic-flex_counter yang model.

2024-08-06 18:41 UTC, vivekrnv commented on dockers/docker-orchagent/enable_counters.py
> +    if platform_info.get('switch_type', '') == 'dpu':
updated

2024-08-06 18:41 UTC, vivekrnv commented
@dgsudharsan Added yang model

2024-08-20 17:33 UTC, dgsudharsan approved these changes

2024-08-23 15:11 UTC, closed without merging